name: miraculous_myths_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+2

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  dots_indicator: ^2.0.0
  get: ^4.6.5
  url_launcher: ^6.1.10
  youtube_player_flutter: ^8.1.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # LOGO
     - images/logo.png

      # THUMBNAIL HOME SCREEN
     - images/season1.jpg
     - images/season2.jpg
     - images/season3.jpg
     - images/season4.jpg
     - images/season5.jpg
     - images/special.jpg
     - images/Shanghai.jpg
     - images/Awaking.jpg
     - images/Welcome.png
     - images/login.png
     - images/sign-up.png



      # THUMBNAIL SEASON 1
     - images/S1/E1.jpg
     - images/S1/E2.jpg
     - images/S1/E3.jpg
     - images/S1/E4.jpg
     - images/S1/E5.jpg
     - images/S1/E6.jpg
     - images/S1/E7.jpg
     - images/S1/E8.jpg
     - images/S1/E9.jpg
     - images/S1/E10.jpg
     - images/S1/E11.jpg
     - images/S1/E12.jpg
     - images/S1/E13.jpg
     - images/S1/E14.jpg
     - images/S1/E15.jpg
     - images/S1/E16.jpg
     - images/S1/E17.jpg
     - images/S1/E18.jpg
     - images/S1/E19.jpg
     - images/S1/E20.jpg
     - images/S1/E21.jpg
     - images/S1/E22.jpg
     - images/S1/E23.jpg
     - images/S1/E24.jpg
     - images/S1/E25.jpg
     - images/S1/E26.jpg

      # THUMBNAIL SEASON 2
     - images/S2/E1.jpg
     - images/S2/E2.jpg
     - images/S2/E3.jpg
     - images/S2/E4.jpg
     - images/S2/E5.jpg
     - images/S2/E6.jpg
     - images/S2/E7.jpg
     - images/S2/E8.jpg
     - images/S2/E9.jpg
     - images/S2/E10.jpg
     - images/S2/E11.jpg
     - images/S2/E12.jpg
     - images/S2/E13.jpg
     - images/S2/E14.jpg
     - images/S2/E15.jpg
     - images/S2/E16.jpg
     - images/S2/E17.jpg
     - images/S2/E18.jpg
     - images/S2/E19.jpg
     - images/S2/E20.jpg
     - images/S2/E21.jpg
     - images/S2/E22.jpg
     - images/S2/E23.jpg
     - images/S2/E24.jpg
     - images/S2/E25.jpg
     - images/S2/E26.jpg

      # THUMBNAIL SEASON 3
     - images/S3/E1.jpg
     - images/S3/E2.jpg
     - images/S3/E3.jpg
     - images/S3/E4.jpg
     - images/S3/E5.jpg
     - images/S3/E6.jpg
     - images/S3/E7.jpg
     - images/S3/E8.jpg
     - images/S3/E9.jpg
     - images/S3/E10.jpg
     - images/S3/E11.jpg
     - images/S3/E12.jpg
     - images/S3/E13.jpg
     - images/S3/E14.jpg
     - images/S3/E15.jpg
     - images/S3/E16.jpg
     - images/S3/E17.jpg
     - images/S3/E18.jpg
     - images/S3/E19.png
     - images/S3/E20.jpg
     - images/S3/E21.jpg
     - images/S3/E22.jpg
     - images/S3/E23.jpg
     - images/S3/E24.jpg
     - images/S3/E25.jpg
     - images/S3/E26.jpg

      # THUMBNAIL SEASON 4
     - images/S4/E1.png
     - images/S4/E2.png
     - images/S4/E3.png
     - images/S4/E4.png
     - images/S4/E5.jpg
     - images/S4/E6.png
     - images/S4/E7.png
     - images/S4/E8.png
     - images/S4/E9.png
     - images/S4/E10.png
     - images/S4/E11.png
     - images/S4/E12.png
     - images/S4/E13.png
     - images/S4/E14.png
     - images/S4/E15.png
     - images/S4/E16.png
     - images/S4/E17.png
     - images/S4/E18.png
     - images/S4/E19.png
     - images/S4/E20.png
     - images/S4/E21.png
     - images/S4/E22.jpg
     - images/S4/E23.png
     - images/S4/E24.jpg
     - images/S4/E25.jpg
     - images/S4/E26.jpg

      # THUMBNAIL SEASON 5
     - images/S5/E1.jpg
     - images/S5/E2.png
     - images/S5/E3.jpg
     - images/S5/E4.jpg
     - images/S5/E5.png
     - images/S5/E6.png
     - images/S5/E7.png
     - images/S5/E8.png
     - images/S5/E9.jpg
     - images/S5/E10.jpg
     - images/S5/E11.png
     - images/S5/E12.jpg
     - images/S5/E13.jpg
     - images/S5/E14.jpg
     - images/S5/E15.jpg
     - images/S5/E16.jpg
     - images/S5/E17.jpg
     - images/S5/E18.jpg
     - images/S5/E19.png
     - images/S5/E20.png
     - images/S5/E21.jpg
     - images/S5/E22.jpg
     - images/S5/E23.jpg
     - images/S5/E24.jpg
     - images/S5/E25.jpg
     - images/S5/E26.jpg

  #   - images/a_dot_ham.jpeg

  fonts:
     - family: RemachineScript
       fonts:
         - asset: fonts/RemachineScript.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
     - family: HACEN_BEIRUT
       fonts:
         - asset: fonts/HACEN_BEIRUT.TTF